version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_USER=bensonl
      - MYSQL_PASSWORD=bensonl
      - MYSQL_DATABASE=sales
      - MYSQL_ROOT_PASSWORD=root